project_id = "yqjdzziqdimflzytcpbg"

[functions.detect-wheels]
verify_jwt = false

[functions.render-rims]
verify_jwt = false

[functions.generate-3d]
verify_jwt = false

[functions.check-3d-status]
verify_jwt = false

[functions.proxy-model]
verify_jwt = false